#ifndef LAUNCH_H
#define LAUNCH_H

// command list
enum {
	CPLUS, CMINUS, CMULT, CDIV, CMOD, CIF,
	CWHILE, CPRINT, CPRINTN, CPRINTS, CPRINTLN,
	CSTOP, CDOUBLE, CNONE, CNEG, CNONEP, CINPUT,
	CPLUSA, CMINUSA, CMULTA, CDIVA, CMODA, CASSIGN,
	CLOAD, CEQUAL, CNOTEQ, CMORE, CLESS, CMOREEQ,
	CLESSEQ, CJUMP, CNEGP, CELSE
};

void printCommands();
void launching();

#endif
